### ISSUE TITLE
Roadmap for v1

### ISSUE THREAD

**Issue by codebyaryan** [codebyaryan/canopus#1]
## Canopus GraphQL roadmap
there's a long way to go to make this project usable! This is what we need to implement to get going! If anyone is willing to contribute, please let me know before you start so that we don't overlap each other.
- [ ] Configuration support
- [ ] Caching support
- [ ] Data sources support
- [ ] Apps support
- [ ] Query and mutation support
- [ ] File uploads support
- [ ] Generic mutations and query support (which supports input validation and authorization)
- [ ] Dataloader support
- [ ] Relay support
- [ ] Serve schema via aiohttp/uvicorn
- [ ] GraphiQL support
- [ ] Query Batching support 
- [ ] Middleware support
- [ ] Validation rules support
- [ ] Custom encoder/ error formatter
- [ ] Logging support

To implement along the way:
- Type hints
- Unit tests
- Good documentation 

Maybe in the future:
- [ ] Subscriptions support
- [ ] Performance optimization 
- [ ] Apollo tracing support
